# Generated by Django 5.2.7 on 2025-12-14 15:17

import course_documents.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('principal', '0015_alter_preguntaformulario_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del documento')),
                ('file', models.FileField(upload_to=course_documents.models.course_document_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'ppt', 'pptx', 'xls', 'xlsx', 'txt', 'zip', 'rar', 'jpg', 'jpeg', 'png'])], verbose_name='Archivo')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('file_size', models.PositiveIntegerField(editable=False, verbose_name='Tamaño del archivo (bytes)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': '📄 Documento del Curso',
                'verbose_name_plural': '📄 Documentos del Curso',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessed_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de acceso')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='course_documents.coursedocument', verbose_name='Documento')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': '📊 Acceso a Documento',
                'verbose_name_plural': '📊 Accesos a Documentos',
                'ordering': ['-accessed_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de la carpeta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_folders', to='principal.curso', verbose_name='Curso')),
            ],
            options={
                'verbose_name': '📁 Carpeta de Documentos',
                'verbose_name_plural': '📁 Carpetas de Documentos',
                'ordering': ['name'],
                'unique_together': {('curso', 'name')},
            },
        ),
        migrations.AddField(
            model_name='coursedocument',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='course_documents.documentfolder', verbose_name='Carpeta'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('folder_created', 'Carpeta Creada'), ('folder_deleted', 'Carpeta Eliminada'), ('document_uploaded', 'Documento Subido'), ('document_downloaded', 'Documento Descargado'), ('document_deleted', 'Documento Eliminado'), ('unauthorized_access', 'Acceso No Autorizado')], max_length=20, verbose_name='Acción')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('details', models.TextField(blank=True, null=True, verbose_name='Detalles adicionales')),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.curso', verbose_name='Curso')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course_documents.coursedocument', verbose_name='Documento')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course_documents.documentfolder', verbose_name='Carpeta')),
            ],
            options={
                'verbose_name': '📋 Log de Auditoría',
                'verbose_name_plural': '📋 Logs de Auditoría',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='NewContentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_new_content', models.BooleanField(default=False, verbose_name='Tiene contenido nuevo')),
                ('last_checked', models.DateTimeField(auto_now=True, verbose_name='Última verificación')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.curso', verbose_name='Curso')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': '🔔 Notificación de Contenido Nuevo',
                'verbose_name_plural': '🔔 Notificaciones de Contenido Nuevo',
                'unique_together': {('curso', 'student')},
            },
        ),
    ]
