# Generated by Django 5.2.7 on 2025-12-31 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedocument',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nombre del documento'),
        ),
    ]
