# Generated by Django 5.2.7 on 2025-12-31 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_documents', '0002_alter_coursedocument_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FolderAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_accessed', models.DateTimeField(auto_now=True, verbose_name='Último acceso')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Primer acceso')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='course_documents.documentfolder', verbose_name='Carpeta')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': '📂 Acceso a Carpeta',
                'verbose_name_plural': '📂 Accesos a Carpetas',
                'ordering': ['-last_accessed'],
                'unique_together': {('folder', 'student')},
            },
        ),
    ]
