# Generated by Django 5.2.7 on 2025-12-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_documents', '0002_alter_coursedocument_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('folder_created', 'Carpeta Creada'), ('folder_deleted', 'Carpeta Eliminada'), ('document_uploaded', 'Documento Subido'), ('document_downloaded', 'Documento Descargado'), ('document_deleted', 'Documento Eliminado'), ('unauthorized_access', 'Acceso No Autorizado')], max_length=50, verbose_name='Acción'),
        ),
    ]
