# Generated by Django 5.2.7 on 2026-04-14 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_documents', '0003_folderaccess'),
        ('course_documents', '0003_increase_audit_log_action_length'),
    ]

    operations = [
    ]
