# Generated by Django 5.2.7 on 2026-04-17 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_documents', '0004_merge_20260414_0844'),
        ('principal', '0016_alter_notaindividual_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='principal.curso', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='coursedocument',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre del documento'),
        ),
        migrations.DeleteModel(
            name='FolderAccess',
        ),
    ]
