# Generated by Django 5.2.7 on 2026-07-13 16:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_documents', '0009_add_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='coursedocument',
            name='idx_course_document_folder',
        ),
        migrations.RemoveIndex(
            model_name='coursedocument',
            name='idx_course_document_uploaded_at_desc',
        ),
        migrations.RemoveIndex(
            model_name='coursedocument',
            name='idx_course_document_uploaded_by',
        ),
        migrations.RemoveIndex(
            model_name='documentaccess',
            name='idx_document_access_document',
        ),
        migrations.RemoveIndex(
            model_name='documentaccess',
            name='idx_document_access_student',
        ),
        migrations.RemoveIndex(
            model_name='documentaccess',
            name='idx_document_access_accessed_at_desc',
        ),
        migrations.AddField(
            model_name='coursedocument',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Metadatos del archivo'),
        ),
        migrations.AddField(
            model_name='coursedocument',
            name='processed',
            field=models.BooleanField(default=False, verbose_name='Procesado'),
        ),
        migrations.AddField(
            model_name='coursedocument',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de procesamiento'),
        ),
        migrations.AddField(
            model_name='coursedocument',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Falló')], default='pending', max_length=20, verbose_name='Estado del procesamiento'),
        ),
        migrations.AddField(
            model_name='documentfolder',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='document_folders', to=settings.AUTH_USER_MODEL, verbose_name='Estudiantes con acceso'),
        ),
    ]
