# Generated by Django 5.2.7 on 2026-05-13 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('principal', '0019_add_reglamento_general'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('tipo', models.CharField(choices=[('momentanea', 'Calificación Momentánea'), ('libre', 'Pensamiento Libre')], max_length=20, verbose_name='Tipo')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('publicada', 'Publicada')], default='borrador', max_length=10, verbose_name='Estado')),
                ('fecha_limite', models.DateTimeField(blank=True, null=True, verbose_name='Fecha límite de entrega')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='principal.curso', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Evaluación',
                'verbose_name_plural': 'Evaluaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='IntentoEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('enviado', 'Enviado'), ('calificado', 'Calificado')], default='enviado', max_length=10, verbose_name='Estado')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envío')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos_evaluacion', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='evaluaciones.evaluacion', verbose_name='Evaluación')),
            ],
            options={
                'verbose_name': 'Intento de Evaluación',
                'verbose_name_plural': 'Intentos de Evaluación',
                'unique_together': {('evaluacion', 'estudiante')},
            },
        ),
        migrations.CreateModel(
            name='CalificacionEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Puntaje (0-100)')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentario del profesor')),
                ('es_automatica', models.BooleanField(default=True, verbose_name='Calificación automática')),
                ('fecha_calificacion', models.DateTimeField(auto_now_add=True)),
                ('intento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calificacion', to='evaluaciones.intentoevaluacion', verbose_name='Intento')),
            ],
            options={
                'verbose_name': 'Calificación de Evaluación',
                'verbose_name_plural': 'Calificaciones de Evaluación',
            },
        ),
        migrations.CreateModel(
            name='PreguntaEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=1000, verbose_name='Texto de la pregunta')),
                ('tipo', models.CharField(choices=[('opcion_multiple', 'Opción Múltiple'), ('seleccion_unica', 'Selección Única'), ('verdadero_falso', 'Verdadero / Falso'), ('escritura_libre', 'Escritura Libre')], max_length=20, verbose_name='Tipo')),
                ('requerida', models.BooleanField(default=True, verbose_name='Requerida')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='evaluaciones.evaluacion', verbose_name='Evaluación')),
            ],
            options={
                'verbose_name': 'Pregunta de Evaluación',
                'verbose_name_plural': 'Preguntas de Evaluación',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='OpcionEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=500, verbose_name='Texto de la opción')),
                ('es_correcta', models.BooleanField(default=False, verbose_name='Es correcta')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='evaluaciones.preguntaevaluacion', verbose_name='Pregunta')),
            ],
            options={
                'verbose_name': 'Opción de Evaluación',
                'verbose_name_plural': 'Opciones de Evaluación',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaIntento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_respuesta', models.TextField(blank=True, null=True, verbose_name='Respuesta de texto')),
                ('intento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='evaluaciones.intentoevaluacion', verbose_name='Intento')),
                ('opciones_seleccionadas', models.ManyToManyField(blank=True, related_name='respuestas', to='evaluaciones.opcionevaluacion', verbose_name='Opciones seleccionadas')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.preguntaevaluacion', verbose_name='Pregunta')),
            ],
            options={
                'verbose_name': 'Respuesta de Intento',
                'verbose_name_plural': 'Respuestas de Intento',
                'unique_together': {('intento', 'pregunta')},
            },
        ),
    ]
