# Generated by Django 5.2.7 on 2026-05-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacionevaluacion',
            name='puntaje',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Puntaje (0-10)'),
        ),
    ]
