# Generated by Django 5.2.7 on 2026-05-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0002_alter_calificacion_puntaje_scale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='tipo',
            field=models.CharField(choices=[('momentanea', 'Calificación Momentánea'), ('libre', 'Pensamiento Libre')], default='libre', max_length=20, verbose_name='Tipo'),
        ),
    ]
