# Generated by Django 5.2.7 on 2026-05-16 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0003_alter_evaluacion_tipo_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='preguntaevaluacion',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Puntos que vale esta pregunta (solo para evaluaciones momentáneas)', max_digits=4, verbose_name='Valor (puntos)'),
        ),
    ]
