# Generated by Django 5.2.7 on 2026-05-16 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0004_add_valor_pregunta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='tipo',
            field=models.CharField(choices=[('momentanea', 'Calificación Momentánea'), ('libre', 'Calificación Normal')], default='libre', max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='preguntaevaluacion',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Puntos que vale esta pregunta (solo para evaluaciones momentáneas)', max_digits=4, verbose_name='Valor (puntos)'),
        ),
    ]
