# Generated by Django 5.2.7 on 2026-05-19 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0005_add_valor_pregunta'),
    ]

    operations = [
        migrations.AddField(
            model_name='preguntaevaluacion',
            name='todo_o_nada',
            field=models.BooleanField(default=False, help_text='Si está activo, cualquier error en la pregunta da 0 puntos. Si está inactivo, se descuentan puntos por cada error.', verbose_name='Todo o nada'),
        ),
    ]
