# Generated by Django 5.2.7 on 2025-12-09 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Slug')),
                ('icono', models.CharField(blank=True, help_text='Nombre del icono (ej: book, question-circle)', max_length=50, verbose_name='Icono')),
                ('orden', models.IntegerField(default=0, help_text='Orden de visualización', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Categoría FAQ',
                'verbose_name_plural': 'Categorías FAQ',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ChatInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100, verbose_name='ID de sesión')),
                ('pregunta', models.TextField(verbose_name='Pregunta del usuario')),
                ('respuesta', models.TextField(verbose_name='Respuesta generada')),
                ('documentos_recuperados', models.JSONField(help_text='Lista de documentos encontrados por la búsqueda semántica', verbose_name='Documentos recuperados')),
                ('intencion_detectada', models.CharField(blank=True, max_length=50, null=True, verbose_name='Intención detectada')),
                ('confianza', models.FloatField(help_text='Confianza en la respuesta (0.0 - 1.0)', verbose_name='Nivel de confianza')),
                ('fue_util', models.BooleanField(blank=True, help_text='Feedback del usuario sobre la utilidad de la respuesta', null=True, verbose_name='¿Fue útil?')),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha')),
                ('tiempo_respuesta', models.FloatField(help_text='Tiempo que tomó generar la respuesta', verbose_name='Tiempo de respuesta (segundos)')),
                ('es_candidata_faq', models.BooleanField(default=False, help_text='Marcada como candidata para crear una nueva FAQ', verbose_name='Candidata para FAQ')),
            ],
            options={
                'verbose_name': 'Interacción de Chat',
                'verbose_name_plural': 'Interacciones de Chat',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['-fecha'], name='chatbot_cha_fecha_b4a78d_idx'), models.Index(fields=['session_id'], name='chatbot_cha_session_0187b1_idx'), models.Index(fields=['es_candidata_faq'], name='chatbot_cha_es_cand_7a1ceb_idx')],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=500, verbose_name='Pregunta')),
                ('respuesta', models.TextField(verbose_name='Respuesta')),
                ('prioridad', models.IntegerField(default=0, help_text='Mayor número = mayor prioridad en resultados', verbose_name='Prioridad')),
                ('destacada', models.BooleanField(default=False, help_text='Las FAQs destacadas aparecen primero en los resultados', verbose_name='Destacada')),
                ('activa', models.BooleanField(default=True, help_text='Solo las FAQs activas se incluyen en las búsquedas', verbose_name='Activa')),
                ('veces_usada', models.IntegerField(default=0, help_text='Contador de cuántas veces se ha usado esta FAQ en respuestas', verbose_name='Veces usada')),
                ('ultima_fecha_uso', models.DateTimeField(blank=True, null=True, verbose_name='Última fecha de uso')),
                ('tasa_exito', models.FloatField(default=0.0, help_text='Porcentaje de feedback positivo (0.0 - 1.0)', verbose_name='Tasa de éxito')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='chatbot.categoriafaq', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['-destacada', '-prioridad', '-veces_usada'],
            },
        ),
        migrations.CreateModel(
            name='FAQVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_variacion', models.CharField(help_text='Forma alternativa de hacer la misma pregunta', max_length=500, verbose_name='Variación de la pregunta')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('faq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variaciones', to='chatbot.faq', verbose_name='FAQ')),
            ],
            options={
                'verbose_name': 'Variación de FAQ',
                'verbose_name_plural': 'Variaciones de FAQ',
                'ordering': ['fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='DocumentEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID del objeto')),
                ('texto_indexado', models.TextField(help_text='Texto que fue convertido a embedding', verbose_name='Texto indexado')),
                ('embedding_vector', models.BinaryField(help_text='Embedding serializado con pickle/numpy', verbose_name='Vector de embedding')),
                ('categoria', models.CharField(db_index=True, help_text='Categoría para filtrado (cursos, inscripciones, pagos, etc.)', max_length=50, verbose_name='Categoría')),
                ('fecha_indexacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de indexación')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de contenido')),
            ],
            options={
                'verbose_name': 'Embedding de Documento',
                'verbose_name_plural': 'Embeddings de Documentos',
                'ordering': ['-fecha_indexacion'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='chatbot_doc_content_77fef4_idx'), models.Index(fields=['categoria'], name='chatbot_doc_categor_33ecf3_idx')],
            },
        ),
    ]
