# Generated by Django 5.2.7 on 2025-12-11 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentembedding',
            name='chunk_index',
            field=models.IntegerField(default=0, help_text='Posición del chunk dentro del documento original', verbose_name='Índice del chunk'),
        ),
        migrations.AddField(
            model_name='documentembedding',
            name='chunk_type',
            field=models.CharField(default='text', help_text='Tipo de chunk (question, answer, combined, etc.)', max_length=50, verbose_name='Tipo de chunk'),
        ),
    ]
