# Generated by Django 5.2.7 on 2025-12-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_registro_foto_carnet_registro_foto_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='es_religioso',
            field=models.BooleanField(default=False, verbose_name='Es Religioso'),
        ),
    ]
