# Generated by Django 5.2.7 on 2026-04-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='visibilidad',
            field=models.CharField(choices=[('solo_registrados', 'Solo usuarios registrados'), ('publico', 'Público (cualquier visitante)'), ('indexable', 'Público e indexable en buscadores')], default='publico', help_text='Controla quién puede ver esta noticia y si aparece en buscadores', max_length=20),
        ),
    ]
