# Generated by Django 5.2.7 on 2026-04-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_add_visibilidad_to_noticia'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='permitir_comentarios',
            field=models.BooleanField(default=True, help_text='Permitir que los usuarios comenten esta noticia'),
        ),
    ]
