# Generated by Django 5.2.7 on 2026-06-30 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_add_permitir_comentarios_to_noticia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='nota_moderacion',
            field=models.TextField(blank=True, default='', help_text='Notas internas del moderador (movimientos, auditoría)'),
        ),
        migrations.CreateModel(
            name='ComentarioFijado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_fijado', models.DateTimeField(auto_now_add=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('comentario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fijado', to='blog.comentario')),
                ('fijado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comentarios_fijados', to=settings.AUTH_USER_MODEL)),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_fijados', to='blog.noticia')),
            ],
            options={
                'verbose_name': 'Comentario fijado',
                'verbose_name_plural': 'Comentarios fijados',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='MetricaComunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('total_reportes', models.PositiveIntegerField(default=0)),
                ('total_comentarios', models.PositiveIntegerField(default=0)),
                ('total_sanciones', models.PositiveIntegerField(default=0)),
                ('pico_toxicidad', models.FloatField(blank=True, null=True)),
                ('generada_en', models.DateTimeField(auto_now_add=True)),
                ('usuario_mas_activo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Métrica de comunidad',
                'verbose_name_plural': 'Métricas de comunidad',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ReporteComentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=1000)),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('resuelto_retirado', 'Resuelto - Retirado'), ('resuelto_mantenido', 'Resuelto - Mantenido')], default='pendiente', max_length=20)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='blog.comentario')),
                ('reportado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_enviados', to=settings.AUTH_USER_MODEL)),
                ('resuelto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_resueltos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte de comentario',
                'verbose_name_plural': 'Reportes de comentarios',
                'ordering': ['-fecha_reporte'],
            },
        ),
        migrations.CreateModel(
            name='SancionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_sancion', models.CharField(choices=[('silencio', 'Silencio temporal'), ('baneo_temporal', 'Baneo temporal'), ('baneo_permanente', 'Baneo permanente')], max_length=20)),
                ('motivo', models.CharField(max_length=1000)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_levantamiento', models.DateTimeField(blank=True, null=True)),
                ('aplicada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sanciones_aplicadas', to=settings.AUTH_USER_MODEL)),
                ('levantada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sanciones_levantadas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sanción de usuario',
                'verbose_name_plural': 'Sanciones de usuarios',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
