# Generated by Django 5.2.7 on 2026-07-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comentario_nota_moderacion_comentariofijado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='notas_editor',
            field=models.TextField(blank=True, default='', help_text='Notas del editor al devolver un artículo al autor', max_length=1000),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('pendiente_revision', 'Pendiente de revisión'), ('publicado', 'Publicado'), ('archivado', 'Archivado')], default='borrador', max_length=20),
        ),
    ]
