# Generated by Django 5.2.7 on 2026-07-17 16:25
"""
Migration 0002: Enable PostgreSQL Row-Level Security (RLS).

Implements:
- pgcrypto extension for cryptographic functions
- Row-Level Security on sensitive tables
- RLS policies for hierarchical RBAC (admin > editor > viewer > user)
- Policies for PII, blog content, course documents, and security data

Requirements: 2.7, 2.8
"""

from django.db import migrations


# ═══════════════════════════════════════════════════════════════════════════════
# Helper: SQL templates for RLS policies
# ═══════════════════════════════════════════════════════════════════════════════

# Policy: Usuarios solo ven sus propios datos
POLICY_USER_OWN = (
    "CREATE POLICY {policy_name} ON {table} FOR {command} "
    "TO {roles} USING (user_id = current_setting('rls.user_id')::int OR "
    "current_setting('rls.user_role') IN ('admin', 'superuser'));"
)

# Policy: Roles específicos pueden ver todos los registros
POLICY_ROLE_ACCESS = (
    "CREATE POLICY {policy_name} ON {table} FOR {command} "
    "TO {roles} USING (current_setting('rls.user_role') IN ({allowed_roles}));"
)

# Policy: Solo el dueño o admin puede modificar
POLICY_OWNER_MODIFY = (
    "CREATE POLICY {policy_name} ON {table} FOR {command} "
    "TO {roles} USING ("
    "  (user_id = current_setting('rls.user_id')::int) OR "
    "  (current_setting('rls.user_role') IN ('admin', 'superuser'))"
    ") WITH CHECK ("
    "  (user_id = current_setting('rls.user_id')::int) OR "
    "  (current_setting('rls.user_role') IN ('admin', 'superuser'))"
    ");"
)

# Policy: Lectura para todos los autenticados
POLICY_AUTH_READ = (
    "CREATE POLICY {policy_name} ON {table} FOR SELECT "
    "TO {roles} USING (true);"
)


# ═══════════════════════════════════════════════════════════════════════════════
# SQL functions for forward migration
# ═══════════════════════════════════════════════════════════════════════════════

SQL_ENABLE_PGCRYPTO = "CREATE EXTENSION IF NOT EXISTS pgcrypto;"

SQL_CREATE_RLS_HELPER_FUNCTIONS = """
-- Function to set the RLS context for the current session
CREATE OR REPLACE FUNCTION rls_set_context(user_id int, user_role text)
RETURNS void AS $$
BEGIN
    PERFORM set_config('rls.user_id', user_id::text, false);
    PERFORM set_config('rls.user_role', user_role, false);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Function to get current user ID from RLS context
CREATE OR REPLACE FUNCTION rls_current_user_id()
RETURNS int AS $$
BEGIN
    RETURN current_setting('rls.user_id')::int;
EXCEPTION WHEN OTHERS THEN
    RETURN 0;
END;
$$ LANGUAGE plpgsql STABLE;

-- Function to get current user role from RLS context
CREATE OR REPLACE FUNCTION rls_current_user_role()
RETURNS text AS $$
BEGIN
    RETURN current_setting('rls.user_role');
EXCEPTION WHEN OTHERS THEN
    RETURN 'anonymous';
END;
$$ LANGUAGE plpgsql STABLE;

"""


# ═══════════════════════════════════════════════════════════════════════════════
# Enable RLS on sensitive tables
# ═══════════════════════════════════════════════════════════════════════════════

SQL_ENABLE_RLS = """
-- Accounts: PII data
ALTER TABLE accounts_registro ENABLE ROW LEVEL SECURITY;

-- Blog: Content management
ALTER TABLE blog_noticia ENABLE ROW LEVEL SECURITY;
ALTER TABLE blog_comentario ENABLE ROW LEVEL SECURITY;
ALTER TABLE blog_reportecomentario ENABLE ROW LEVEL SECURITY;
ALTER TABLE blog_sancionusuario ENABLE ROW LEVEL SECURITY;

-- Course Documents: Sensitive educational content
ALTER TABLE course_documents_documentfolder ENABLE ROW LEVEL SECURITY;
ALTER TABLE course_documents_coursedocument ENABLE ROW LEVEL SECURITY;
ALTER TABLE course_documents_documentaccess ENABLE ROW LEVEL SECURITY;
ALTER TABLE course_documents_auditlog ENABLE ROW LEVEL SECURITY;

-- Security: Audit logs and sensitive config
ALTER TABLE security_usersecurityprofile ENABLE ROW LEVEL SECURITY;
ALTER TABLE security_securityauditlog ENABLE ROW LEVEL SECURITY;
ALTER TABLE security_authorizationauditlog ENABLE ROW LEVEL SECURITY;
ALTER TABLE security_role ENABLE ROW LEVEL SECURITY;
ALTER TABLE security_userroleassignment ENABLE ROW LEVEL SECURITY;
ALTER TABLE security_apikey ENABLE ROW LEVEL SECURITY;
ALTER TABLE security_jwtsession ENABLE ROW LEVEL SECURITY;
ALTER TABLE security_objectpermission ENABLE ROW LEVEL SECURITY;
ALTER TABLE security_timebasedaccesspolicy ENABLE ROW LEVEL SECURITY;
ALTER TABLE security_encrypteddatakey ENABLE ROW LEVEL SECURITY;
ALTER TABLE security_wafrule ENABLE ROW LEVEL SECURITY;
ALTER TABLE security_securityreport ENABLE ROW LEVEL SECURITY;
ALTER TABLE security_compliancecheck ENABLE ROW LEVEL SECURITY;
"""


# ═══════════════════════════════════════════════════════════════════════════════
# RLS Policies for accounts
# ═══════════════════════════════════════════════════════════════════════════════

SQL_ACCOUNTS_POLICIES = """
-- accounts_registro: PII - user sees own, admins see all
DROP POLICY IF EXISTS accounts_registro_user_select ON accounts_registro;
CREATE POLICY accounts_registro_user_select ON accounts_registro FOR SELECT
    USING (
        user_id = rls_current_user_id()
        OR rls_current_user_role() IN ('admin', 'superuser')
    );

DROP POLICY IF EXISTS accounts_registro_user_modify ON accounts_registro;
CREATE POLICY accounts_registro_user_modify ON accounts_registro FOR UPDATE
    USING (user_id = rls_current_user_id())
    WITH CHECK (user_id = rls_current_user_id());

DROP POLICY IF EXISTS accounts_registro_admin_modify ON accounts_registro;
CREATE POLICY accounts_registro_admin_modify ON accounts_registro FOR ALL
    USING (rls_current_user_role() IN ('admin', 'superuser'))
    WITH CHECK (rls_current_user_role() IN ('admin', 'superuser'));
"""


# ═══════════════════════════════════════════════════════════════════════════════
# RLS Policies for blog (Noticias, Comentarios, Reportes, Sanciones)
# ═══════════════════════════════════════════════════════════════════════════════

SQL_BLOG_POLICIES = """
-- blog_noticia: Role-based visibility
-- Publicado/public: visible to all authenticated
-- Borrador: only author and editors+
DROP POLICY IF EXISTS blog_noticia_select ON blog_noticia;
CREATE POLICY blog_noticia_select ON blog_noticia FOR SELECT
    USING (
        estado = 'publicado'
        OR autor_id = rls_current_user_id()
        OR rls_current_user_role() IN ('editor', 'admin', 'superuser')
    );

DROP POLICY IF EXISTS blog_noticia_insert ON blog_noticia;
CREATE POLICY blog_noticia_insert ON blog_noticia FOR INSERT
    WITH CHECK (rls_current_user_role() IN ('editor', 'admin', 'superuser', 'author'));

DROP POLICY IF EXISTS blog_noticia_modify ON blog_noticia;
CREATE POLICY blog_noticia_modify ON blog_noticia FOR UPDATE
    USING (
        autor_id = rls_current_user_id()
        OR rls_current_user_role() IN ('editor', 'admin', 'superuser')
    ) WITH CHECK (
        autor_id = rls_current_user_id()
        OR rls_current_user_role() IN ('editor', 'admin', 'superuser')
    );

DROP POLICY IF EXISTS blog_noticia_delete ON blog_noticia;
CREATE POLICY blog_noticia_delete ON blog_noticia FOR DELETE
    USING (rls_current_user_role() IN ('admin', 'superuser'));

-- blog_comentario: Author owns comments, moderators manage all
DROP POLICY IF EXISTS blog_comentario_select ON blog_comentario;
CREATE POLICY blog_comentario_select ON blog_comentario FOR SELECT
    USING (true);

DROP POLICY IF EXISTS blog_comentario_insert ON blog_comentario;
CREATE POLICY blog_comentario_insert ON blog_comentario FOR INSERT
    WITH CHECK (true);

DROP POLICY IF EXISTS blog_comentario_moderate ON blog_comentario;
CREATE POLICY blog_comentario_moderate ON blog_comentario FOR UPDATE
    USING (
        autor_id = rls_current_user_id()
        OR rls_current_user_role() IN ('admin', 'superuser', 'moderator')
    );

-- blog_reportecomentario: Only moderators+ can see all reports
DROP POLICY IF EXISTS blog_reportes_select ON blog_reportecomentario;
CREATE POLICY blog_reportes_select ON blog_reportecomentario FOR SELECT
    USING (rls_current_user_role() IN ('admin', 'superuser', 'moderator'));

DROP POLICY IF EXISTS blog_reportes_insert ON blog_reportecomentario;
CREATE POLICY blog_reportes_insert ON blog_reportecomentario FOR INSERT
    WITH CHECK (reportado_por_id = rls_current_user_id());

-- blog_sancionusuario: Only admins manage sanctions
DROP POLICY IF EXISTS blog_sanciones_select ON blog_sancionusuario;
CREATE POLICY blog_sanciones_select ON blog_sancionusuario FOR SELECT
    USING (
        usuario_id = rls_current_user_id()
        OR rls_current_user_role() IN ('admin', 'superuser')
    );

DROP POLICY IF EXISTS blog_sanciones_manage ON blog_sancionusuario;
CREATE POLICY blog_sanciones_manage ON blog_sancionusuario FOR ALL
    USING (rls_current_user_role() IN ('admin', 'superuser'))
    WITH CHECK (rls_current_user_role() IN ('admin', 'superuser'));
"""


# ═══════════════════════════════════════════════════════════════════════════════
# RLS Policies for course_documents
# ═══════════════════════════════════════════════════════════════════════════════

SQL_COURSE_DOCUMENTS_POLICIES = """
-- course_documents_documentfolder: Teachers/admins manage, students see related
DROP POLICY IF EXISTS doc_folder_select ON course_documents_documentfolder;
CREATE POLICY doc_folder_select ON course_documents_documentfolder FOR SELECT
    USING (
        created_by_id = rls_current_user_id()
        OR rls_current_user_role() IN ('admin', 'superuser', 'teacher', 'professor')
    );

DROP POLICY IF EXISTS doc_folder_manage ON course_documents_documentfolder;
CREATE POLICY doc_folder_manage ON course_documents_documentfolder FOR ALL
    USING (created_by_id = rls_current_user_id() OR rls_current_user_role() IN ('admin', 'superuser'))
    WITH CHECK (created_by_id = rls_current_user_id() OR rls_current_user_role() IN ('admin', 'superuser'));

-- course_documents_coursedocument: Teachers see own, admins see all, students see enrolled
DROP POLICY IF EXISTS doc_coursedocument_select ON course_documents_coursedocument;
CREATE POLICY doc_coursedocument_select ON course_documents_coursedocument FOR SELECT
    USING (
        uploaded_by_id = rls_current_user_id()
        OR rls_current_user_role() IN ('admin', 'superuser', 'teacher', 'professor')
    );

DROP POLICY IF EXISTS doc_coursedocument_manage ON course_documents_coursedocument;
CREATE POLICY doc_coursedocument_manage ON course_documents_coursedocument FOR ALL
    USING (uploaded_by_id = rls_current_user_id() OR rls_current_user_role() IN ('admin', 'superuser'))
    WITH CHECK (uploaded_by_id = rls_current_user_id() OR rls_current_user_role() IN ('admin', 'superuser'));

-- course_documents_documentaccess: Users see own access logs only
DROP POLICY IF EXISTS doc_access_select ON course_documents_documentaccess;
CREATE POLICY doc_access_select ON course_documents_documentaccess FOR SELECT
    USING (
        student_id = rls_current_user_id()
        OR rls_current_user_role() IN ('admin', 'superuser', 'teacher', 'professor')
    );

DROP POLICY IF EXISTS doc_access_insert ON course_documents_documentaccess;
CREATE POLICY doc_access_insert ON course_documents_documentaccess FOR INSERT
    WITH CHECK (student_id = rls_current_user_id());

-- course_documents_auditlog: Only admins see audit logs
DROP POLICY IF EXISTS doc_auditlog_select ON course_documents_auditlog;
CREATE POLICY doc_auditlog_select ON course_documents_auditlog FOR SELECT
    USING (rls_current_user_role() IN ('admin', 'superuser'));
"""


# ═══════════════════════════════════════════════════════════════════════════════
# RLS Policies for security tables
# ═══════════════════════════════════════════════════════════════════════════════

SQL_SECURITY_POLICIES = """
-- security_usersecurityprofile: Users see own profile, admins see all
DROP POLICY IF EXISTS sec_profile_select ON security_usersecurityprofile;
CREATE POLICY sec_profile_select ON security_usersecurityprofile FOR SELECT
    USING (
        user_id = rls_current_user_id()
        OR rls_current_user_role() IN ('admin', 'superuser')
    );

DROP POLICY IF EXISTS sec_profile_manage ON security_usersecurityprofile;
CREATE POLICY sec_profile_manage ON security_usersecurityprofile FOR ALL
    USING (user_id = rls_current_user_id() OR rls_current_user_role() IN ('admin', 'superuser'))
    WITH CHECK (user_id = rls_current_user_id() OR rls_current_user_role() IN ('admin', 'superuser'));

-- security_securityauditlog: Only admins see audit logs
DROP POLICY IF EXISTS sec_auditlog_select ON security_securityauditlog;
CREATE POLICY sec_auditlog_select ON security_securityauditlog FOR SELECT
    USING (rls_current_user_role() IN ('admin', 'superuser'));

DROP POLICY IF EXISTS sec_auditlog_insert ON security_securityauditlog;
CREATE POLICY sec_auditlog_insert ON security_securityauditlog FOR INSERT
    WITH CHECK (true);

-- security_authorizationauditlog: Only admins
DROP POLICY IF EXISTS sec_authzaudit_select ON security_authorizationauditlog;
CREATE POLICY sec_authzaudit_select ON security_authorizationauditlog FOR SELECT
    USING (rls_current_user_role() IN ('admin', 'superuser'));

DROP POLICY IF EXISTS sec_authzaudit_insert ON security_authorizationauditlog;
CREATE POLICY sec_authzaudit_insert ON security_authorizationauditlog FOR INSERT
    WITH CHECK (true);

-- security_role / security_userroleassignment: Only admins
DROP POLICY IF EXISTS sec_role_select ON security_role;
CREATE POLICY sec_role_select ON security_role FOR SELECT
    USING (rls_current_user_role() IN ('admin', 'superuser'));

DROP POLICY IF EXISTS sec_role_manage ON security_role;
CREATE POLICY sec_role_manage ON security_role FOR ALL
    USING (rls_current_user_role() IN ('admin', 'superuser'))
    WITH CHECK (rls_current_user_role() IN ('admin', 'superuser'));

DROP POLICY IF EXISTS sec_roleassignment_select ON security_userroleassignment;
CREATE POLICY sec_roleassignment_select ON security_userroleassignment FOR SELECT
    USING (rls_current_user_role() IN ('admin', 'superuser'));

DROP POLICY IF EXISTS sec_roleassignment_manage ON security_userroleassignment;
CREATE POLICY sec_roleassignment_manage ON security_userroleassignment FOR ALL
    USING (rls_current_user_role() IN ('admin', 'superuser'))
    WITH CHECK (rls_current_user_role() IN ('admin', 'superuser'));

-- security_apikey: Users see own keys, admins see all
DROP POLICY IF EXISTS sec_apikey_select ON security_apikey;
CREATE POLICY sec_apikey_select ON security_apikey FOR SELECT
    USING (
        user_id = rls_current_user_id()
        OR rls_current_user_role() IN ('admin', 'superuser')
    );

DROP POLICY IF EXISTS sec_apikey_manage ON security_apikey;
CREATE POLICY sec_apikey_manage ON security_apikey FOR ALL
    USING (user_id = rls_current_user_id() OR rls_current_user_role() IN ('admin', 'superuser'))
    WITH CHECK (user_id = rls_current_user_id() OR rls_current_user_role() IN ('admin', 'superuser'));

-- security_jwtsession: Users see own sessions
DROP POLICY IF EXISTS sec_jwtsession_select ON security_jwtsession;
CREATE POLICY sec_jwtsession_select ON security_jwtsession FOR SELECT
    USING (
        user_id = rls_current_user_id()
        OR rls_current_user_role() IN ('admin', 'superuser')
    );

-- security_objectpermission: Admins manage permissions
DROP POLICY IF EXISTS sec_objperm_select ON security_objectpermission;
CREATE POLICY sec_objperm_select ON security_objectpermission FOR SELECT
    USING (rls_current_user_role() IN ('admin', 'superuser'));

DROP POLICY IF EXISTS sec_objperm_manage ON security_objectpermission;
CREATE POLICY sec_objperm_manage ON security_objectpermission FOR ALL
    USING (rls_current_user_role() IN ('admin', 'superuser'))
    WITH CHECK (rls_current_user_role() IN ('admin', 'superuser'));

-- security_encrypteddatakey: Only admins
DROP POLICY IF EXISTS sec_encryptkey_select ON security_encrypteddatakey;
CREATE POLICY sec_encryptkey_select ON security_encrypteddatakey FOR SELECT
    USING (rls_current_user_role() IN ('admin', 'superuser'));

-- security_wafrule: Only admins view/modify
DROP POLICY IF EXISTS sec_wafrule_select ON security_wafrule;
CREATE POLICY sec_wafrule_select ON security_wafrule FOR SELECT
    USING (rls_current_user_role() IN ('admin', 'superuser'));

DROP POLICY IF EXISTS sec_wafrule_manage ON security_wafrule;
CREATE POLICY sec_wafrule_manage ON security_wafrule FOR ALL
    USING (rls_current_user_role() IN ('admin', 'superuser'))
    WITH CHECK (rls_current_user_role() IN ('admin', 'superuser'));

-- security_securityreport: Only admins
DROP POLICY IF EXISTS sec_report_select ON security_securityreport;
CREATE POLICY sec_report_select ON security_securityreport FOR SELECT
    USING (rls_current_user_role() IN ('admin', 'superuser'));

-- security_compliancecheck: Only admins
DROP POLICY IF EXISTS sec_compliance_select ON security_compliancecheck;
CREATE POLICY sec_compliance_select ON security_compliancecheck FOR SELECT
    USING (rls_current_user_role() IN ('admin', 'superuser'));
"""


# ═══════════════════════════════════════════════════════════════════════════════
# Reverse SQL: Drop all policies and disable RLS
# ═══════════════════════════════════════════════════════════════════════════════

SQL_REVERSE_POLICIES = """
-- Drop accounts policies
DROP POLICY IF EXISTS accounts_registro_user_select ON accounts_registro;
DROP POLICY IF EXISTS accounts_registro_user_modify ON accounts_registro;
DROP POLICY IF EXISTS accounts_registro_admin_modify ON accounts_registro;

-- Drop blog policies
DROP POLICY IF EXISTS blog_noticia_select ON blog_noticia;
DROP POLICY IF EXISTS blog_noticia_insert ON blog_noticia;
DROP POLICY IF EXISTS blog_noticia_modify ON blog_noticia;
DROP POLICY IF EXISTS blog_noticia_delete ON blog_noticia;
DROP POLICY IF EXISTS blog_comentario_select ON blog_comentario;
DROP POLICY IF EXISTS blog_comentario_insert ON blog_comentario;
DROP POLICY IF EXISTS blog_comentario_moderate ON blog_comentario;
DROP POLICY IF EXISTS blog_reportes_select ON blog_reportecomentario;
DROP POLICY IF EXISTS blog_reportes_insert ON blog_reportecomentario;
DROP POLICY IF EXISTS blog_sanciones_select ON blog_sancionusuario;
DROP POLICY IF EXISTS blog_sanciones_manage ON blog_sancionusuario;

-- Drop course documents policies
DROP POLICY IF EXISTS doc_folder_select ON course_documents_documentfolder;
DROP POLICY IF EXISTS doc_folder_manage ON course_documents_documentfolder;
DROP POLICY IF EXISTS doc_coursedocument_select ON course_documents_coursedocument;
DROP POLICY IF EXISTS doc_coursedocument_manage ON course_documents_coursedocument;
DROP POLICY IF EXISTS doc_access_select ON course_documents_documentaccess;
DROP POLICY IF EXISTS doc_access_insert ON course_documents_documentaccess;
DROP POLICY IF EXISTS doc_auditlog_select ON course_documents_auditlog;

-- Drop security policies
DROP POLICY IF EXISTS sec_profile_select ON security_usersecurityprofile;
DROP POLICY IF EXISTS sec_profile_manage ON security_usersecurityprofile;
DROP POLICY IF EXISTS sec_auditlog_select ON security_securityauditlog;
DROP POLICY IF EXISTS sec_auditlog_insert ON security_securityauditlog;
DROP POLICY IF EXISTS sec_authzaudit_select ON security_authorizationauditlog;
DROP POLICY IF EXISTS sec_authzaudit_insert ON security_authorizationauditlog;
DROP POLICY IF EXISTS sec_role_select ON security_role;
DROP POLICY IF EXISTS sec_role_manage ON security_role;
DROP POLICY IF EXISTS sec_roleassignment_select ON security_userroleassignment;
DROP POLICY IF EXISTS sec_roleassignment_manage ON security_userroleassignment;
DROP POLICY IF EXISTS sec_apikey_select ON security_apikey;
DROP POLICY IF EXISTS sec_apikey_manage ON security_apikey;
DROP POLICY IF EXISTS sec_jwtsession_select ON security_jwtsession;
DROP POLICY IF EXISTS sec_objperm_select ON security_objectpermission;
DROP POLICY IF EXISTS sec_objperm_manage ON security_objectpermission;
DROP POLICY IF EXISTS sec_encryptkey_select ON security_encrypteddatakey;
DROP POLICY IF EXISTS sec_wafrule_select ON security_wafrule;
DROP POLICY IF EXISTS sec_wafrule_manage ON security_wafrule;
DROP POLICY IF EXISTS sec_report_select ON security_securityreport;
DROP POLICY IF EXISTS sec_compliance_select ON security_compliancecheck;

-- Disable RLS on all tables
ALTER TABLE accounts_registro DISABLE ROW LEVEL SECURITY;
ALTER TABLE blog_noticia DISABLE ROW LEVEL SECURITY;
ALTER TABLE blog_comentario DISABLE ROW LEVEL SECURITY;
ALTER TABLE blog_reportecomentario DISABLE ROW LEVEL SECURITY;
ALTER TABLE blog_sancionusuario DISABLE ROW LEVEL SECURITY;
ALTER TABLE course_documents_documentfolder DISABLE ROW LEVEL SECURITY;
ALTER TABLE course_documents_coursedocument DISABLE ROW LEVEL SECURITY;
ALTER TABLE course_documents_documentaccess DISABLE ROW LEVEL SECURITY;
ALTER TABLE course_documents_auditlog DISABLE ROW LEVEL SECURITY;
ALTER TABLE security_usersecurityprofile DISABLE ROW LEVEL SECURITY;
ALTER TABLE security_securityauditlog DISABLE ROW LEVEL SECURITY;
ALTER TABLE security_authorizationauditlog DISABLE ROW LEVEL SECURITY;
ALTER TABLE security_role DISABLE ROW LEVEL SECURITY;
ALTER TABLE security_userroleassignment DISABLE ROW LEVEL SECURITY;
ALTER TABLE security_apikey DISABLE ROW LEVEL SECURITY;
ALTER TABLE security_jwtsession DISABLE ROW LEVEL SECURITY;
ALTER TABLE security_objectpermission DISABLE ROW LEVEL SECURITY;
ALTER TABLE security_timebasedaccesspolicy DISABLE ROW LEVEL SECURITY;
ALTER TABLE security_encrypteddatakey DISABLE ROW LEVEL SECURITY;
ALTER TABLE security_wafrule DISABLE ROW LEVEL SECURITY;
ALTER TABLE security_securityreport DISABLE ROW LEVEL SECURITY;
ALTER TABLE security_compliancecheck DISABLE ROW LEVEL SECURITY;

-- Drop helper functions
DROP FUNCTION IF EXISTS rls_set_context(int, text);
DROP FUNCTION IF EXISTS rls_current_user_id();
DROP FUNCTION IF EXISTS rls_current_user_role();

"""


# ═══════════════════════════════════════════════════════════════════════════════
# Migration Operations
# ═══════════════════════════════════════════════════════════════════════════════

class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
        ('accounts', '0010_registro_es_religioso'),
        ('blog', '0006_update_tipo_sancion_choices'),
        ('course_documents', '0008_documentfolder_curso_id_original'),
    ]

    operations = [
        # Step 1: Enable pgcrypto extension
        migrations.RunSQL(
            sql=SQL_ENABLE_PGCRYPTO,
            reverse_sql=migrations.RunSQL.noop,
            state_operations=None,
        ),

        # Step 2: Create helper functions for RLS context
        migrations.RunSQL(
            sql=SQL_CREATE_RLS_HELPER_FUNCTIONS,
            reverse_sql=SQL_REVERSE_POLICIES,
        ),

        # Step 3: Enable RLS on all sensitive tables
        migrations.RunSQL(
            sql=SQL_ENABLE_RLS,
            reverse_sql=SQL_REVERSE_POLICIES,
        ),

        # Step 4: Create RLS policies for accounts (PII data)
        migrations.RunSQL(
            sql=SQL_ACCOUNTS_POLICIES,
            reverse_sql=SQL_REVERSE_POLICIES,
        ),

        # Step 5: Create RLS policies for blog
        migrations.RunSQL(
            sql=SQL_BLOG_POLICIES,
            reverse_sql=SQL_REVERSE_POLICIES,
        ),

        # Step 6: Create RLS policies for course_documents
        migrations.RunSQL(
            sql=SQL_COURSE_DOCUMENTS_POLICIES,
            reverse_sql=SQL_REVERSE_POLICIES,
        ),

        # Step 7: Create RLS policies for security
        migrations.RunSQL(
            sql=SQL_SECURITY_POLICIES,
            reverse_sql=SQL_REVERSE_POLICIES,
        ),
    ]
