# Generated by Django 5.2.7 on 2026-04-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_archivados', '0005_add_combinado_fields_to_datoarchivadodinamico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notaindividualarchivada',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor de la Nota'),
        ),
    ]
