# Generated by Django 5.2.7 on 2026-05-08 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_archivados', '0007_cursoarchivado_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReglamentoCursoArchivado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_original', models.IntegerField(verbose_name='ID Original del ReglamentoCurso')),
                ('introduccion', models.TextField(blank=True, default='', verbose_name='Introducción')),
                ('fecha_creacion', models.DateTimeField(verbose_name='Fecha de creación original')),
                ('fecha_migracion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de migración')),
                ('curso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reglamento_archivado', to='datos_archivados.cursoarchivado', verbose_name='Curso Archivado')),
            ],
            options={
                'verbose_name': 'Reglamento de Curso Archivado',
                'verbose_name_plural': 'Reglamentos de Cursos Archivados',
            },
        ),
        migrations.CreateModel(
            name='ArticuloReglamentoArchivado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_original', models.IntegerField(verbose_name='ID Original del ArticuloReglamento')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del artículo')),
                ('cuerpo', models.TextField(max_length=5000, verbose_name='Cuerpo del artículo')),
                ('orden', models.PositiveIntegerField(default=1, verbose_name='Orden')),
                ('fecha_creacion', models.DateTimeField(verbose_name='Fecha de creación original')),
                ('fecha_migracion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de migración')),
                ('reglamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulos', to='datos_archivados.reglamentocursoarchivado', verbose_name='Reglamento Archivado')),
            ],
            options={
                'verbose_name': 'Artículo de Reglamento Archivado',
                'verbose_name_plural': 'Artículos de Reglamentos Archivados',
                'ordering': ['orden', 'fecha_creacion'],
            },
        ),
    ]
