# Generated by Django 5.2.7 on 2026-05-23 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_archivados', '0008_add_reglamento_archivado'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemestreCursoArchivado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_original', models.IntegerField(db_index=True, verbose_name='ID Original del SemestreCurso')),
                ('numero_semestre', models.PositiveIntegerField(verbose_name='Número de Semestre')),
                ('activo', models.BooleanField(default=False, verbose_name='Activo al momento del archivado')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('fecha_cierre', models.DateField(blank=True, null=True, verbose_name='Fecha de cierre')),
                ('fecha_creacion', models.DateTimeField(verbose_name='Fecha de creación original')),
                ('fecha_migracion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de migración')),
                ('curso_academico_archivado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semestres_archivados', to='datos_archivados.cursoacademicoarchivado', verbose_name='Curso Académico Archivado')),
                ('curso_archivado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semestres_archivados', to='datos_archivados.cursoarchivado', verbose_name='Curso Archivado')),
            ],
            options={
                'verbose_name': 'Semestre de Curso Archivado',
                'verbose_name_plural': 'Semestres de Cursos Archivados',
                'ordering': ['numero_semestre'],
            },
        ),
    ]
