# Generated by Django 5.2.7 on 2026-05-28 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_archivados', '0009_semestrecursoarchivado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matriculaarchivada',
            name='estado',
            field=models.CharField(choices=[('P', 'Activo'), ('A', 'Aprobado'), ('BA', 'Baja por Ausencia'), ('BL', 'Baja por Licencia'), ('BI', 'Baja por Insuficiencia Académica'), ('R', 'Reprobado'), ('L', 'Licencia'), ('B', 'Baja')], default='P', max_length=2, verbose_name='Estado'),
        ),
    ]
