# Generated by Django 5.2.7 on 2026-05-29 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_archivados', '0010_fix_matricula_archivada_estado_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistenciaarchivada',
            name='semestre_archivado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias', to='datos_archivados.semestrecursoarchivado', verbose_name='Semestre Archivado'),
        ),
        migrations.AddField(
            model_name='calificacionarchivada',
            name='semestre_archivado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calificaciones', to='datos_archivados.semestrecursoarchivado', verbose_name='Semestre Archivado'),
        ),
        migrations.AddField(
            model_name='matriculaarchivada',
            name='semestre_archivado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matriculas', to='datos_archivados.semestrecursoarchivado', verbose_name='Semestre Archivado'),
        ),
    ]
