# Generated by Django 5.2.1 on 2025-05-31 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_alter_curso_options_matriculas_activo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_1', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nota 1')),
                ('nota_2', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nota 2')),
                ('nota_3', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nota 3')),
                ('nota_4', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nota 4')),
                ('nota_5', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nota 5')),
                ('nota_6', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nota 6')),
                ('average', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Promedio')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.curso', verbose_name='Curso')),
                ('student', models.ForeignKey(limit_choices_to={'groups__name': 'Estudiantes'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Estudiante')),
            ],
        ),
    ]
