# Generated by Django 5.2.1 on 2025-05-31 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_calificaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificaciones',
            name='average',
            field=models.DecimalField(blank=True, decimal_places=1, editable='False', max_digits=3, null=True, verbose_name='Promedio'),
        ),
    ]
