# Generated by Django 5.2.1 on 2025-06-01 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_alter_calificaciones_average'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='status',
            field=models.CharField(choices=[('I', 'En etapa de inscripcion'), ('P', 'En progreso'), ('F', 'Finalizado')], default='I', max_length=15, verbose_name='Estado'),
        ),
    ]
