# Generated by Django 5.2.1 on 2025-06-05 15:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0007_curso_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calificaciones',
            options={'verbose_name': 'Calificacion', 'verbose_name_plural': 'Calificaciones'},
        ),
        migrations.AlterUniqueTogether(
            name='calificaciones',
            unique_together={('course', 'student')},
        ),
    ]
