# Generated by Django 5.2.1 on 2025-06-05 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0008_alter_calificaciones_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calificaciones',
            options={},
        ),
    ]
