# Generated by Django 5.2.1 on 2025-06-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0009_alter_calificaciones_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='image',
            field=models.ImageField(default='default/plantilla.jpg', upload_to='imagenes/', verbose_name='Imagen de curso'),
        ),
    ]
