# Generated by Django 5.2.7 on 2025-12-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0015_alter_preguntaformulario_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notaindividual',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor de la Nota'),
        ),
    ]
