# Generated by Django 5.2.7 on 2026-05-08 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0017_add_fecha_campos_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReglamentoCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduccion', models.TextField(blank=True, default='', verbose_name='Introducción')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('curso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reglamento_curso', to='principal.curso', verbose_name='Curso')),
            ],
            options={
                'verbose_name': '📄 Reglamento del Curso',
                'verbose_name_plural': '📄 Reglamentos de Cursos',
            },
        ),
        migrations.CreateModel(
            name='ArticuloReglamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del artículo')),
                ('cuerpo', models.TextField(max_length=5000, verbose_name='Cuerpo del artículo')),
                ('orden', models.PositiveIntegerField(default=1, verbose_name='Orden')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('reglamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulos', to='principal.reglamentocurso', verbose_name='Reglamento')),
            ],
            options={
                'verbose_name': '📝 Artículo de Reglamento',
                'verbose_name_plural': '📝 Artículos de Reglamento',
                'ordering': ['orden', 'fecha_creacion'],
            },
        ),
    ]
