# Generated by Django 5.2.7 on 2026-05-16 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0004_add_valor_pregunta'),
        ('principal', '0019_add_reglamento_general'),
    ]

    operations = [
        migrations.AddField(
            model_name='notaindividual',
            name='evaluacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_individuales', to='evaluaciones.evaluacion', verbose_name='Evaluación origen'),
        ),
    ]
