# Generated by Django 5.2.7 on 2026-05-23 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0020_add_evaluacion_to_nota_individual'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemestreCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_semestre', models.PositiveIntegerField(help_text='Valor mínimo: 1', verbose_name='Número de Semestre')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('fecha_cierre', models.DateField(blank=True, null=True, verbose_name='Fecha de cierre')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semestres', to='principal.curso', verbose_name='Curso')),
                ('curso_academico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semestres_curso', to='principal.cursoacademico', verbose_name='Curso Académico')),
            ],
            options={
                'verbose_name': 'Semestre del Curso',
                'verbose_name_plural': 'Semestres del Curso',
                'ordering': ['numero_semestre'],
            },
        ),
    ]
