# Generated by Django 5.2.7 on 2026-05-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0021_semestrecurso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matriculas',
            name='estado',
            field=models.CharField(choices=[('P', 'Activo'), ('A', 'Aprobado'), ('R', 'Reprobado'), ('BA', 'Baja por Ausencia'), ('BL', 'Baja por Licencia'), ('BI', 'Baja por Insuficiencia Académica')], default='P', max_length=2, verbose_name='Estado'),
        ),
    ]
