# Generated by Django 5.2.7 on 2026-05-29 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0023_remove_reprobado_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='semestre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias', to='principal.semestrecurso', verbose_name='Semestre'),
        ),
        migrations.AddField(
            model_name='calificaciones',
            name='semestre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calificaciones', to='principal.semestrecurso', verbose_name='Semestre'),
        ),
        migrations.AddField(
            model_name='matriculas',
            name='semestre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matriculas', to='principal.semestrecurso', verbose_name='Semestre'),
        ),
    ]
