# Generated by Django 5.2.7 on 2026-06-20 14:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0025_solicitudinscripcion_curso_academico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='calificaciones',
            unique_together={('course', 'student', 'curso_academico', 'semestre')},
        ),
    ]
