# Generated by Django 5.2.7 on 2026-07-26 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0026_calificaciones_unique_with_semestre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada')], default='pending', max_length=20, verbose_name='Estado')),
                ('submission_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de solicitud')),
                ('processed_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de procesamiento')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notas')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='principal.curso', verbose_name='Curso')),
                ('student', models.ForeignKey(limit_choices_to={'groups__name': 'Estudiantes'}, on_delete=django.db.models.deletion.CASCADE, related_name='course_applications', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Solicitud de curso',
                'verbose_name_plural': 'Solicitudes de cursos',
                'ordering': ['-submission_date'],
                'indexes': [models.Index(fields=['student', 'status'], name='principal_c_student_142de5_idx'), models.Index(fields=['course', 'status'], name='principal_c_course__6a41c1_idx'), models.Index(fields=['-submission_date'], name='principal_c_submiss_54647f_idx')],
                'unique_together': {('course', 'student', 'status')},
            },
        ),
    ]
