# Generated by Django 5.2.7 on 2026-03-13 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_archivados', '0004_codigoverificacionreclamacion'),
        ('historial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_original', models.IntegerField()),
                ('tabla_origen', models.CharField(max_length=255)),
                ('fecha_consolidacion', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('classbody', models.TextField()),
                ('uploaddate', models.DateField()),
                ('datepub', models.DateTimeField()),
                ('dateend', models.DateTimeField()),
                ('slug', models.CharField(max_length=250)),
                ('dato_archivado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historical_classes', to='datos_archivados.datoarchivadodinamico')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='historial.historicalsubjectinformation')),
            ],
            options={
                'verbose_name': 'Historical Class',
                'verbose_name_plural': 'Historical Classes',
                'db_table': 'historial_docenciaclass',
            },
        ),
        migrations.CreateModel(
            name='HistoricalClassStudentView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_original', models.IntegerField()),
                ('tabla_origen', models.CharField(max_length=255)),
                ('fecha_consolidacion', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_views', to='historial.historicalapplication')),
                ('class_field', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, related_name='student_views', to='historial.historicalclass')),
                ('dato_archivado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historical_class_student_views', to='datos_archivados.datoarchivadodinamico')),
            ],
            options={
                'verbose_name': 'Historical Class Student View',
                'verbose_name_plural': 'Historical Class Student Views',
                'db_table': 'historial_docenciaclass_studentview',
                'unique_together': {('class_field', 'application')},
            },
        ),
    ]
