# Generated by Django 5.2.7 on 2026-03-13 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0002_historicalclass_historicalclassstudentview'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='historicalcourseinformationadminteachers',
            table='historial_docenciacourseinformation_adminteachers',
        ),
    ]
