# Generated by Django 5.2.7 on 2026-03-01 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('codigo', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Historical Area',
                'verbose_name_plural': 'Historical Areas',
                'db_table': 'historial_docenciaarea',
            },
        ),
        migrations.CreateModel(
            name='HistoricalAccountNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuenta', models.CharField(max_length=100)),
                ('banco', models.CharField(blank=True, max_length=255, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_numbers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historical Account Number',
                'verbose_name_plural': 'Historical Account Numbers',
                'db_table': 'historial_docenciaaccountnumber',
            },
        ),
        migrations.CreateModel(
            name='HistoricalCourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('anio_maximo', models.IntegerField(blank=True, null=True)),
                ('anio_minimo', models.IntegerField(blank=True, null=True)),
                ('capacidad', models.IntegerField(blank=True, null=True)),
                ('codigo', models.CharField(blank=True, max_length=50, null=True)),
                ('comunicado', models.TextField(blank=True, null=True)),
                ('creditos_minimos', models.IntegerField(blank=True, null=True)),
                ('curriculum', models.TextField(blank=True, null=True)),
                ('duracion', models.CharField(blank=True, max_length=100, null=True)),
                ('es_servicio', models.BooleanField()),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_limite', models.DateField(blank=True, null=True)),
                ('imagen', models.CharField(blank=True, max_length=500, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_religioso', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('programa', models.TextField(blank=True, null=True)),
                ('registro_abierto', models.BooleanField()),
                ('reglamento', models.TextField(blank=True, null=True)),
                ('requisitos', models.TextField(blank=True, null=True)),
                ('slug', models.CharField(blank=True, max_length=255, null=True)),
                ('tiene_solicitud', models.BooleanField()),
                ('visible', models.BooleanField()),
                ('visible_comunicado', models.BooleanField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='historial.historicalcoursecategory')),
            ],
            options={
                'verbose_name': 'Historical Course Category',
                'verbose_name_plural': 'Historical Course Categories',
                'db_table': 'historial_docenciacoursecategory',
            },
        ),
        migrations.CreateModel(
            name='HistoricalCourseInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('codigo', models.CharField(blank=True, max_length=50, null=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='historial.historicalarea')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='historial.historicalcoursecategory')),
            ],
            options={
                'verbose_name': 'Historical Course Information',
                'verbose_name_plural': 'Historical Course Information',
                'db_table': 'historial_docenciacourseinformation',
            },
        ),
        migrations.CreateModel(
            name='HistoricalEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='editions', to='historial.historicalcourseinformation')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='editions_instructed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historical Edition',
                'verbose_name_plural': 'Historical Editions',
                'db_table': 'historial_docenciaedition',
            },
        ),
        migrations.CreateModel(
            name='HistoricalApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('beca', models.IntegerField()),
                ('pagado', models.IntegerField()),
                ('nota_primaria', models.IntegerField()),
                ('nota_secundaria', models.IntegerField()),
                ('nota_final', models.IntegerField()),
                ('nota_extra', models.IntegerField()),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='historial.historicalcourseinformation')),
                ('edicion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='historial.historicaledition')),
            ],
            options={
                'verbose_name': 'Historical Application',
                'verbose_name_plural': 'Historical Applications',
                'db_table': 'historial_docenciaapplication',
            },
        ),
        migrations.CreateModel(
            name='HistoricalEnrollmentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField()),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_applications', to='historial.historicalcourseinformation')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historical Enrollment Application',
                'verbose_name_plural': 'Historical Enrollment Applications',
                'db_table': 'historial_docenciaenrollmentapplication',
            },
        ),
        migrations.CreateModel(
            name='HistoricalEnrollmentPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateTimeField()),
                ('metodo_pago', models.CharField(blank=True, max_length=100, null=True)),
                ('aceptado', models.BooleanField()),
                ('cuenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='historial.historicalaccountnumber')),
                ('solicitud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='historial.historicalenrollmentapplication')),
            ],
            options={
                'verbose_name': 'Historical Enrollment Pay',
                'verbose_name_plural': 'Historical Enrollment Pays',
                'db_table': 'historial_docenciaenrollmentpay',
            },
        ),
        migrations.CreateModel(
            name='HistoricalSubjectInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('codigo', models.CharField(blank=True, max_length=50, null=True)),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='historial.historicalcourseinformation')),
            ],
            options={
                'verbose_name': 'Historical Subject Information',
                'verbose_name_plural': 'Historical Subject Information',
                'db_table': 'historial_docenciasubjectinformation',
            },
        ),
        migrations.CreateModel(
            name='HistoricalEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField()),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('ausencias', models.IntegerField()),
                ('intento', models.IntegerField()),
                ('nota_extra', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nota_final', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nota_primaria', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nota_secundaria', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('slug', models.CharField(blank=True, max_length=255, null=True)),
                ('edicion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='historial.historicaledition')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='historial.historicalsubjectinformation')),
            ],
            options={
                'verbose_name': 'Historical Enrollment',
                'verbose_name_plural': 'Historical Enrollments',
                'db_table': 'historial_docenciaenrollment',
            },
        ),
        migrations.CreateModel(
            name='HistoricalCourseInformationAdminTeachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_teachers', to='historial.historicalcourseinformation')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administered_courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historical Course Information Admin Teacher',
                'verbose_name_plural': 'Historical Course Information Admin Teachers',
                'db_table': 'Docencia_courseinformation_adminteachers',
                'unique_together': {('curso', 'profesor')},
            },
        ),
    ]
